spring:
  application:
    name: english-output-trainer

  datasource:
    url: jdbc:postgresql://localhost:5432/english_output_trainer
    username: postgres
    password: su839045yx
    # driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never
  
  # Messageプロパティ
  messages:
    basename: messages,validationMessages
    
 # Tomcat設定
server:
  servlet:
    session:
      timeout: 1m