spring:
  application:
    name: english-output-trainer-local

app:
  environment: local
  
log:
  file:
    path: ${LOG_FILE_PATH:./english-output-trainer.log}
    pattern: ${log.file.path}-%d{yyyy-MM-dd}.log.zip