spring:
  application:
    name: english-output-trainer-dev

app:
  environment: dev
  
log:
  file:
    path: ${LOG_FILE_PATH:./english-output-trainer-dev.log}
    pattern: ${log.file.path}-%d{yyyy-MM-dd}.log.zip  