spring.application.name=english-output-trainer

spring.datasource.url=jdbc:postgresql://localhost:5432/english_output_trainer
spring.datasource.username=postgres
spring.datasource.password=su839045yx
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always